"""empty message

Revision ID: 1b2b05dcbbd7
Revises: f11e12b4b36a
Create Date: 2023-01-22 12:14:22.413909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b2b05dcbbd7'
down_revision = 'f11e12b4b36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_constraint('Artist_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['website'])
        batch_op.create_unique_constraint(None, ['name', 'city', 'state'])

    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name', 'city', 'state'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('Artist_name_key', ['name'])

    # ### end Alembic commands ###
