"""empty message

Revision ID: 9f3fcefb7377
Revises: 1b2b05dcbbd7
Create Date: 2023-01-23 05:52:57.945801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3fcefb7377'
down_revision = '1b2b05dcbbd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.drop_constraint('Artist_website_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Artist', schema=None) as batch_op:
        batch_op.create_unique_constraint('Artist_website_key', ['website'])

    # ### end Alembic commands ###
